name: CI
on:
  push:
    - master
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:steps:
  - uses: actions/checkout@master
  - uses: actions/setup-node@v1
    with:
      node-version: '12.x'
  - run: npm ci
  - run: npm run lint
  - run: npm run test
  - uses: codecov/codecov-action@v1
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
